# Rust formatting configuration
# See: https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true

# Comments
wrap_comments = true
comment_width = 80
normalize_comments = true

# Misc
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
